# **Logistic Regression Implementation**

In [1]:
import numpy as npimpo
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

Create dataset

In [3]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=15)

train_test_split

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [5]:
X_train.shape,y_test.shape

((700, 10), (300,))

model training

In [6]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [7]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_pred = logistic.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 0 0]


### performance metrics

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [10]:
score = accuracy_score(y_test,y_pred)
print(score)

0.9166666666666666


In [11]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[146  11]
 [ 14 129]]


In [12]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



## Hyperparameter Tuning And Cross Validation

In [13]:
model = LogisticRegression()
penalty=['l1','l2','elasticnet']
C_values=[100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs', 'liblinear','sag', 'saga']


In [14]:
params = dict(penalty = penalty, C=C_values,solver=solver)

## GridSearchCV
GridSearchCV is a hyperparameter tuning technique in Scikit-Learn that automatically searches through all possible combinations of specified hyperparameter values and finds the combination that gives the best model performance using cross-validation.

In [15]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
cv = StratifiedKFold() ## CrossValidation
grid =GridSearchCV(estimator=model, param_grid=params,scoring='accuracy',cv=cv, n_jobs=-1)

1. estimator=model → The ML model you want to tune.
2. param_grid=params → Dictionary of hyperparameters to test.
3. scoring='accuracy' → Metric used to select the best model.
4. cv=cv → Cross-validation strategy.
5. n_jobs=-1 → Uses all CPU cores to speed up training.

In [16]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [17]:
grid.fit(X_train,y_train)

c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packa

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [18]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [19]:
grid.best_score_

0.9242857142857142

In [20]:
y_pred=grid.predict(X_test)

In [21]:
score = accuracy_score(y_test,y_pred)
print(score)

0.92


In [22]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[149   8]
 [ 16 127]]


In [23]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.90      0.95      0.93       157
           1       0.94      0.89      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



## RandomizedSearchCV
RandomizedSearchCV is a hyperparameter tuning technique in Scikit-Learn that randomly selects a specified number of hyperparameter combinations from a given search space and evaluates them using cross-validation.

In [24]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=model, param_distributions=params,scoring='accuracy',cv=5)

In [25]:
randomcv.fit(X_train,y_train)

c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [26]:
randomcv.best_score_

0.9128571428571428

In [27]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 10}

In [28]:
y_pred=randomcv.predict(X_test)

In [32]:
score = accuracy_score(y_test,y_pred)
print("Score:",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion matrix:\n",cm)
cr = classification_report(y_test,y_pred)
print("Classification Report:",cr)

Score: 0.9166666666666666
confusion matrix:
 [[146  11]
 [ 14 129]]
Classification Report:               precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

