# **K Nearest Neighbor(KNN) Classifier**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

X,y = make_classification(
    n_samples=1000,
    n_features = 3,
    n_redundant=1,
    n_classes = 2,
    random_state=999
)

In [4]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
classifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred=classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [11]:
acs=  accuracy_score(y_test, y_pred)
clr=classification_report(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("accurancy score: \n",acs)
print('confusion matrix\n',cm)
print('classification report:\n',clr)


accurancy score: 
 0.906060606060606
confusion matrix
 [[158  11]
 [ 20 141]]
classification report:
               precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



### Task
used GridSearchCV for i k =1,2,3,4,5,6,7,8,9,10

In [12]:
from sklearn.model_selection import GridSearchCV

In [13]:
param_grid = {
    'n_neighbors':[1,2,3,4,5,6,7,8,9,10]
}

In [14]:
grid = GridSearchCV(
    estimator=classifier,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)

In [17]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [18]:
print(grid.best_params_)

{'n_neighbors': 9}


In [19]:
print(grid.best_score_)

0.9029850746268657


In [20]:
best_knn = grid.best_estimator_

In [21]:
y_pred = best_knn.predict(X_test)

In [22]:
acs=  accuracy_score(y_test, y_pred)
clr=classification_report(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("accurancy score: \n",acs)
print('confusion matrix\n',cm)
print('classification report:\n',clr)


accurancy score: 
 0.9121212121212121
confusion matrix
 [[156  13]
 [ 16 145]]
classification report:
               precision    recall  f1-score   support

           0       0.91      0.92      0.91       169
           1       0.92      0.90      0.91       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

